"""
NPM SDK Publisher — packages and publishes generated TypeScript SDKs to npm.
"""
import os
import json
import shutil
import logging
import subprocess
import tempfile
import re

logger = logging.getLogger(__name__)


def extract_ts_code(raw_text: str) -> str:
    """Extract TypeScript code from AI response, stripping markdown fences."""
    text = raw_text.strip()
    # Remove markdown code fences
    patterns = [
        r"```typescript\s*\n?(.*?)\n?\s*```",
        r"```ts\s*\n?(.*?)\n?\s*```",
        r"```\s*\n?(.*?)\n?\s*```",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1).strip()
    # If no fences, return as-is
    return text


def publish_sdk_to_npm(slug: str, sdk_code: str, project_name: str, gateway_url: str, version: str = "1.0.0") -> dict:
    """
    Package and publish a TypeScript SDK to npm.

    Returns dict with:
      - success: bool
      - packageName: str
      - version: str
      - error: str (if failed)
    """
    npm_token = os.environ.get("NPM_TOKEN", "")
    npm_org = os.environ.get("NPM_ORG", "@scalable")

    if not npm_token:
        return {"success": False, "packageName": "", "version": version, "error": "NPM_TOKEN not configured"}

    package_name = f"{npm_org}/{slug}"

    # Clean the SDK code (strip markdown fences if present)
    clean_sdk = extract_ts_code(sdk_code)

    # Create temp directory for the package
    tmp_dir = tempfile.mkdtemp(prefix=f"scalable-sdk-{slug}-")

    try:
        # 1. Write .npmrc with auth token
        npmrc_path = os.path.join(tmp_dir, ".npmrc")
        with open(npmrc_path, "w") as f:
            f.write(f"//registry.npmjs.org/:_authToken={npm_token}\n")

        # 2. Write package.json
        pkg_json = {
            "name": package_name,
            "version": version,
            "description": f"TypeScript SDK for the {project_name} API. Auto-generated by Scalable.",
            "main": "dist/index.js",
            "types": "dist/index.d.ts",
            "files": ["dist"],
            "scripts": {
                "build": "tsc"
            },
            "keywords": ["api", "sdk", slug, "scalable"],
            "license": "MIT",
            "dependencies": {
                "axios": "^1.7.0"
            },
            "devDependencies": {
                "typescript": "^5.0.0"
            },
            "repository": {
                "type": "git",
                "url": f"https://github.com/scalable-platform/{slug}-sdk"
            },
            "publishConfig": {
                "access": "public"
            }
        }
        with open(os.path.join(tmp_dir, "package.json"), "w") as f:
            json.dump(pkg_json, f, indent=2)

        # 3. Write tsconfig.json
        tsconfig = {
            "compilerOptions": {
                "target": "ES2020",
                "module": "commonjs",
                "lib": ["ES2020"],
                "declaration": True,
                "strict": True,
                "noImplicitAny": False,
                "strictNullChecks": False,
                "outDir": "./dist",
                "rootDir": "./src",
                "esModuleInterop": True,
                "skipLibCheck": True,
                "forceConsistentCasingInFileNames": True,
                "resolveJsonModule": True,
                "moduleResolution": "node"
            },
            "include": ["src/**/*"],
            "exclude": ["node_modules", "dist"]
        }
        with open(os.path.join(tmp_dir, "tsconfig.json"), "w") as f:
            json.dump(tsconfig, f, indent=2)

        # 4. Write SDK source
        src_dir = os.path.join(tmp_dir, "src")
        os.makedirs(src_dir, exist_ok=True)
        with open(os.path.join(src_dir, "index.ts"), "w") as f:
            f.write(clean_sdk)

        # 5. Write README.md
        readme = f"""# {package_name}

TypeScript SDK for the **{project_name}** API.

Auto-generated by [Scalable](https://scalable.app) — Turn your SaaS into a Platform.

## Installation

```bash
npm install {package_name}
```

## Quick Start

```typescript
import {{ ScalableClient }} from '{package_name}';

const client = new ScalableClient({{
  apiKey: 'YOUR_API_KEY',
  baseUrl: '{gateway_url}'  // optional, defaults to production
}});

// Example: List resources
const data = await client.orders.list();
console.log(data);
```

## Authentication

All requests require an API key passed via the `X-API-Key` header.
The SDK handles this automatically when you initialize the client.

## Rate Limiting

The API enforces rate limits per key. Check response headers:
- `X-RateLimit-Limit`: Max requests per minute
- `X-RateLimit-Remaining`: Remaining requests in current window

## License

MIT
"""
        with open(os.path.join(tmp_dir, "README.md"), "w") as f:
            f.write(readme)

        # 6. Install dependencies and compile
        logger.info(f"Installing dependencies in {tmp_dir}")
        install_result = subprocess.run(
            ["npm", "install", "--ignore-scripts"],
            cwd=tmp_dir,
            capture_output=True,
            text=True,
            timeout=60,
        )
        if install_result.returncode != 0:
            logger.warning(f"npm install warnings: {install_result.stderr}")

        logger.info("Compiling TypeScript SDK")
        compile_result = subprocess.run(
            ["npx", "tsc"],
            cwd=tmp_dir,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if compile_result.returncode != 0:
            # If tsc fails, create a JS fallback manually
            logger.warning(f"TypeScript compilation failed: {compile_result.stderr}")
            logger.info("Creating JavaScript fallback")
            dist_dir = os.path.join(tmp_dir, "dist")
            os.makedirs(dist_dir, exist_ok=True)

            # Write a simple JS version by stripping type annotations
            js_code = clean_sdk
            # Basic type stripping - remove type annotations for a JS fallback
            js_code = re.sub(r':\s*\w+(\[\])?(\s*\|[^,;=})\n]+)?(?=\s*[,;=})\n])', '', js_code)
            js_code = re.sub(r'<[^>]+>', '', js_code)
            js_code = re.sub(r'\bexport\s+interface\s+\w+\s*\{[^}]*\}', '', js_code)
            js_code = re.sub(r'\binterface\s+\w+\s*\{[^}]*\}', '', js_code)
            js_code = re.sub(r'\bpublic\s+', '', js_code)
            js_code = re.sub(r'\bprivate\s+', '', js_code)
            js_code = re.sub(r'\bas\s+\w+', '', js_code)

            with open(os.path.join(dist_dir, "index.js"), "w") as f:
                f.write('"use strict";\nObject.defineProperty(exports, "__esModule", { value: true });\n')
                f.write(js_code)

            # Write a minimal .d.ts
            with open(os.path.join(dist_dir, "index.d.ts"), "w") as f:
                f.write(clean_sdk)

        # 7. Publish to npm
        logger.info(f"Publishing {package_name}@{version} to npm")
        publish_result = subprocess.run(
            ["npm", "publish", "--access", "public"],
            cwd=tmp_dir,
            capture_output=True,
            text=True,
            timeout=60,
        )

        combined_output = (publish_result.stdout or "") + (publish_result.stderr or "")

        # npm writes notices to stderr even on success. Check for actual success indicator
        success_published = (
            f"+ {package_name}@" in combined_output
            or f"📦  {package_name}@{version}" in combined_output
        )

        if success_published or publish_result.returncode == 0:
            actual_version = version
            # Try to extract actual version from output
            import re as re_mod
            ver_match = re_mod.search(rf'\+ {re_mod.escape(package_name)}@([\d.]+)', combined_output)
            if ver_match:
                actual_version = ver_match.group(1)
            logger.info(f"Successfully published {package_name}@{actual_version}")
            return {"success": True, "packageName": package_name, "version": actual_version, "error": ""}

        # Check for version conflict
        if "EPUBLISHCONFLICT" in combined_output or "cannot publish over" in combined_output or "previously published" in combined_output:
            logger.info("Version conflict, trying to bump patch version")
            parts = version.split(".")
            parts[-1] = str(int(parts[-1]) + 1)
            new_version = ".".join(parts)

            pkg_json["version"] = new_version
            with open(os.path.join(tmp_dir, "package.json"), "w") as f:
                json.dump(pkg_json, f, indent=2)

            publish_result = subprocess.run(
                ["npm", "publish", "--access", "public"],
                cwd=tmp_dir,
                capture_output=True,
                text=True,
                timeout=60,
            )
            combined_output2 = (publish_result.stdout or "") + (publish_result.stderr or "")
            success_retry = (
                f"+ {package_name}@" in combined_output2 
                or publish_result.returncode == 0
                or f"📦  {package_name}@{new_version}" in combined_output2
            )

            if success_retry:
                logger.info(f"Published {package_name}@{new_version}")
                return {"success": True, "packageName": package_name, "version": new_version, "error": ""}
            else:
                error_msg = combined_output2[:500]
                logger.error(f"npm publish retry failed: {error_msg}")
                return {"success": False, "packageName": package_name, "version": new_version, "error": error_msg}

        # Check if maybe it DID publish despite non-zero exit (npm quirk)
        if f"📦  {package_name}@{version}" in combined_output:
            logger.info(f"npm returned non-zero but package appears published: {package_name}@{version}")
            return {"success": True, "packageName": package_name, "version": version, "error": ""}

        error_msg = combined_output[:500]
        logger.error(f"npm publish failed (rc={publish_result.returncode}): {error_msg}")
        return {"success": False, "packageName": package_name, "version": version, "error": error_msg}

    except subprocess.TimeoutExpired:
        return {"success": False, "packageName": package_name, "version": version, "error": "npm publish timed out"}
    except Exception as e:
        logger.error(f"SDK publish error: {e}")
        return {"success": False, "packageName": package_name, "version": version, "error": str(e)}
    finally:
        # Clean up temp directory
        try:
            shutil.rmtree(tmp_dir, ignore_errors=True)
        except Exception:
            pass
